FROM golang:1.6

ENV SRC /go/src/github.com/voyages-sncf-technologies/strowgr/registrator

RUN go get github.com/docker/engine-api
RUN go get github.com/vdemeester/docker-events
RUN go get github.com/Sirupsen/logrus
RUN go get github.com/samalba/dockerclient

RUN mkdir -p $SRC
WORKDIR $SRC

COPY . .
